### ISSUE TITLE
update libavr32

### ISSUE THREAD

**Issue by tehn** [scanner-darkly/multipass#10]
i was about to update libavr32--- would you like to redirect the submodule to the monome repo? or simply update your fork?

**Comment by scanner-darkly** [comment]
had to look at old commits to remember why i used my own fork - looks like i had some fixes for HID and I2C, the latter i think was already merged to libavr32 but i need to do a pull request for the former. will do it sometime this week and then we can point the submodule to the monome repo!

**Comment by scanner-darkly** [comment]
fixed in cdb49309df8c9f0ccc32a840b11877016fd9335d
