### ISSUE TITLE
draw_str always assumes a black background for the line region

### ISSUE THREAD

**Issue by shankararunachalam** [scanner-darkly/multipass#5]
draw_str receives a background param, but it uses it only for the font background. The line region is always filled with 0. So, the font becomes illegible. Using the background color on region_fill call will fix this. I can submit a pull request for the same, if that is fine.

**Comment by scanner-darkly** [comment]
thank you for the report and the fix! before i merge, just to make sure i understand correctly: does it actually render the background behind the font with the background colour? say, if you called it with `colour` set to 0 and `background` set to 15, do you get black letters on fully lit background, and the rest of the line is black? basically, not sure about this part: "the font becomes illegible"

**Comment by shankararunachalam** [comment]
Attaching quick screenshots. First pic is how it is before the fix. Second pic is after the fix. Sorry for the bad lighting and background color :). Basically, the font gets the background, but the empty pixels between two letters are still black. So, it makes it difficult to read the text. 

![tt1](https://user-images.githubusercontent.com/9945613/68176551-46ff0f80-ff53-11e9-9d61-2e3b632b6898.jpg)
![tt2](https://user-images.githubusercontent.com/9945613/68176560-4a929680-ff53-11e9-9fa4-c7fdd1471afe.jpg)

**Comment by scanner-darkly** [comment]
thanks for the pics - i see what you mean! yeah, makes sense to do the whole line with that background.

**Comment by shankararunachalam** [comment]
Awesome, thanks for merging.
