### ISSUE TITLE
Teletype gate interrupt handler has incorrect event type

### ISSUE THREAD

**Issue by shankararunachalam** [scanner-darkly/multipass#7]
In multipass/monome_euro/libavr32/src/init_teletype.c, line 81 defines the event for the gate interrupt handler. The event type is given as kEventTrigger. This doesn't work since in multipass/monome_euro/main.c the trigger event handler handler_tr is mapped only to an event type named kEventTr. 

The fix would be to change the event type in init_teletype.c to kEventTr. Alternatively, we could change main.c, but init_ansible.c also uses kEventTr for its interrupt handler. So, it is better to just fix it in init_teletype.c and have main.c continue to only react to kEventTr. 

I found the issue while trying to use the trigger inputs of TT. After the suggested fix, the TT triggers are received properly. 

I will submit a pull request for the same. Thanks!

**Comment by shankararunachalam** [comment]
I didn't grasp that libavr32 is a submodule. I guess fixing main.c in multipass is an easier proposition. we could assign the same handler_tr to both kEventTr and kEventTrigger event types. I tested that fix and it works as well. Will make the pull request for this change instead.

@scanner-darkly, does that make sense or would you propose a different fix?

**Comment by scanner-darkly** [comment]
i remember there was weirdness around that, thank you for fixing it!
don't know if you saw, i posted doc on how to use voice allocation and note functions: https://github.com/scanner-darkly/multipass/wiki/voices-and-notes

**Comment by shankararunachalam** [comment]
Thanks for merging. Yes, I saw the document just today morning. Thanks for putting that together! Highly useful. I didn't realize that you already had the note_v functions for microtonal scales. I coded for set_cv since I only noted the chromatic semitones in music.c file. The voice mapping approach will make the code more flexible. So, I am going to try switching to voice mapping with note_v instead, and see if all my code still works well.

**Comment by scanner-darkly** [comment]
yeah, the cool thing about it - it simplifies i2c implementation since all you have to do is assign a voice to an i2c  device and enable the leader mode!

**Comment by shankararunachalam** [comment]
Ah, nice! Time to hook up Just Friends to play nice with my code :).

**Comment by scanner-darkly** [comment]
for JF also remember to add `set_jf_mode(1);` to enable the synth mode
